image: islamic-network/php74

cache:
  key: "$CI_BUILD_NAME_$CI_BUILD_REF_NAME"
  untracked: true
  paths:
    - /root/.composer

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - composer install --dev --prefer-dist --no-interaction
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    expire_in: 1 week
    untracked: true

test:
  stage: test
  only:
    - master
  script:
    - phpunit --coverage-text --colors=never --coverage-html tests/report
  artifacts:
      paths:
        - tests/report

